"""
Generate pytest test files for iOS Recorder --unit_test capture mode.
Called by POST /api/unit_test/save after fixture files are written.

Five test files are maintained (append-only):
  test_gen1_action_coords.py    — Test 1: call _record_* directly → verify action + coords
  test_gen2_hit_test.py         — Test 2: coordinate + hierarchy → element
  test_gen3_step_json.py        — Test 3: call _record_* directly → verify full step JSON
  test_gen4_selector_quality.py — Test 4: selector quality / is problematic
  test_gen5_codegen.py          — Test 5: codegen → Python code

Ground-truth answers are stored in test_unittest/answers/<fixture_key>.json.
On first run the computed result is stored as the answer (test always passes).
Subsequent runs compare against the stored answer (regression detection).
"""
from pathlib import Path
from typing import List

_TEST_UNITTEST = Path(__file__).parent.parent / "test_unittest"

_FILES = {
    1: ("test_gen1_action_coords.py",    "Test 1 — Action + Coordinates: call recorder directly, verify action + coords"),
    2: ("test_gen2_hit_test.py",         "Test 2 — Hit-test: coordinate + hierarchy → element + selector"),
    3: ("test_gen3_step_json.py",        "Test 3 — Full step JSON: call recorder directly, verify step dict output"),
    4: ("test_gen4_selector_quality.py", "Test 4 — Selector quality / is-problematic flag"),
    5: ("test_gen5_codegen.py",          "Test 5 — Codegen: step → generated Python code"),
    6: ("test_gen3b_xpath_variant.py",   "Test 3b — XPath-variant: element id stripped, verifies structural xpath is produced"),
}


# ── File header (written once when the file is first created) ─────────────────

def _file_header(desc: str) -> str:
    return "\n".join([
        '"""',
        "Auto-generated by iOS Recorder --unit_test mode. Append-only.",
        desc,
        '"""',
        "import asyncio",
        "import json",
        "import xml.etree.ElementTree as ET",
        "from pathlib import Path",
        "",
        "import app.main as m",
        "import pytest",
        "from app.hittest import hit_test",
        "from app.selector import build_selector, get_selector_quality",
        "from app.codegen import generate_script",
        "",
        "pytestmark = pytest.mark.unit",
        "",
        '_FIXTURE_DIR = Path(__file__).parent / "fixtures"',
        '_ANSWERS_DIR = Path(__file__).parent / "answers"',
        '_WARN_QUALITIES = frozenset({"id_indexed", "id_eq_label", "label_only", "xpath_only"})',
        '_STRIP_KEYS = frozenset({"timestamp", "pre_screenshot", "pre_screenshot_size"})',
        "",
        "",
        "def _call_record_fn(inp: dict):",
        '    """Directly invoke the recorder\'s _record_* function for the given input."""',
        '    action = inp["action"]',
        '    root = m._cache.get("root")',
        '    if action in ("tap", "double_tap", "triple_tap", "two_finger_tap", "five_tap"):',
        '        asyncio.run(m._record_point(action, inp["x"], inp["y"], root))',
        '    elif action == "long_press":',
        '        asyncio.run(m._record_long_press(inp["x"], inp["y"], inp.get("duration", 1000), root))',
        '    elif action == "multi_finger_tap":',
        '        asyncio.run(m._record_multi_finger_tap(inp["x"], inp["y"], inp.get("fingers", 3), root))',
        '    elif action == "pinch":',
        '        asyncio.run(m._record_pinch(inp["x"], inp["y"], inp["scale"], 80, inp.get("duration", 500), root))',
        '    elif action == "rotate":',
        '        asyncio.run(m._record_rotate(inp["x"], inp["y"], inp["rotation"], 80, root))',
        '    elif action == "scroll":',
        '        asyncio.run(m._record_scroll(inp["x1"], inp["y1"], inp["x2"], inp["y2"], inp.get("duration", 600), root))',
        '    elif action == "swipe":',
        '        asyncio.run(m._record_move("swipe", inp["x1"], inp["y1"], inp["x2"], inp["y2"], inp.get("duration", 400), snapshot=root))',
        '    elif action == "drag":',
        '        asyncio.run(m._record_drag(inp["x1"], inp["y1"], inp["x2"], inp["y2"], inp.get("duration", 1000), root))',
        '    elif action == "type_text":',
        '        asyncio.run(m._record_type_text(inp["text"], inp.get("target_x"), inp.get("target_y"), root))',
        '    elif action == "home":',
        '        asyncio.run(m._record_simple("home"))',
        '    elif action == "launch_app":',
        '        asyncio.run(m._record_launch_app(inp["bundle_id"]))',
        '    elif action == "terminate_app":',
        '        asyncio.run(m._record_terminate_app(inp["bundle_id"]))',
        '    elif action in ("verify_visible", "verify_not_visible"):',
        '        asyncio.run(m._record_verify_visible(inp["target_x"], inp["target_y"],',
        '                                              action == "verify_not_visible", root))',
        '    elif action == "verify_get_text":',
        '        asyncio.run(m._record_verify_get_text(inp["target_x"], inp["target_y"], inp["expected_text"]))',
        '    elif action == "verify_screenshot_gt":',
        '        if "bounds" not in inp:',
        '            pytest.skip("no bounds captured for verify_screenshot_gt")',
        '        asyncio.run(m._record_verify_screenshot_gt(inp["target_x"], inp["target_y"],',
        '                                                   inp["screenshot_name"], inp["bounds"]))',
        '    elif action == "verify_screenshot_diff":',
        '        if "bounds" not in inp:',
        '            pytest.skip("no bounds captured for verify_screenshot_diff")',
        '        asyncio.run(m._record_verify_screenshot_diff(inp["target_x"], inp["target_y"],',
        '                                                     inp["bounds"], inp.get("phase", "before")))',
        '    else:',
        '        pytest.skip(f"unsupported action: {action}")',
        "",
        "",
        "def _load_or_store(fixture_key: str, step_key: str, result):",
        '    """Fail on first run (saving result as answer); compare on subsequent runs."""',
        "    _ANSWERS_DIR.mkdir(exist_ok=True)",
        '    answer_file = _ANSWERS_DIR / f"{fixture_key}.json"',
        "    answers = json.loads(answer_file.read_text()) if answer_file.exists() else {}",
        "    if step_key not in answers:",
        "        answers[step_key] = result",
        "        answer_file.write_text(json.dumps(answers, ensure_ascii=False, indent=2))",
        '        pytest.fail(f"No answer — result saved as new answer:\\n{json.dumps(result, ensure_ascii=False, indent=2)}")',
        "    return answers[step_key]",
        "",
    ]) + "\n"


# ── Per-test function body generators ─────────────────────────────────────────

def _body_t1(fk: str, i: int) -> str:
    fn = f"test_gen1_{fk}_step_{i:03d}"
    sk = f"step_{i:03d}_t1"
    return f"""
def {fn}():
    cap = json.loads((_FIXTURE_DIR / "{fk}" / "capture.json").read_text())
    entry = cap["entries"][{i}]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "{fk}" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {{"action": step["action"]}}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("{fk}", "{sk}", result)
    assert result == answer
"""


def _body_t2(fk: str, i: int) -> str:
    fn = f"test_gen2_{fk}_step_{i:03d}"
    sk = f"step_{i:03d}_t2"
    return f"""
def {fn}():
    cap = json.loads((_FIXTURE_DIR / "{fk}" / "capture.json").read_text())
    entry = cap["entries"][{i}]
    hfile = entry.get("hierarchy_file")
    if not hfile:
        pytest.skip("no hierarchy for this step")
    inp = entry["input"]
    x = inp.get("x", inp.get("x1", inp.get("target_x")))
    y = inp.get("y", inp.get("y1", inp.get("target_y")))
    if x is None or y is None:
        pytest.skip("no coordinates for this step")
    root = ET.fromstring((_FIXTURE_DIR / "{fk}" / hfile).read_text())
    el = hit_test(x, y, root)
    if el is not None:
        sel_type, sel_val = build_selector(el)
        result = {{"type": sel_type, "value": sel_val}}
    else:
        result = {{"type": "coordinate", "value": None}}
    answer = _load_or_store("{fk}", "{sk}", result)
    assert result == answer
"""


def _body_t3(fk: str, i: int) -> str:
    fn = f"test_gen3_{fk}_step_{i:03d}"
    sk = f"step_{i:03d}_t3"
    return f"""
def {fn}():
    cap = json.loads((_FIXTURE_DIR / "{fk}" / "capture.json").read_text())
    entry = cap["entries"][{i}]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "{fk}" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {{k: v for k, v in step.items() if k not in _STRIP_KEYS}}
    answer = _load_or_store("{fk}", "{sk}", result)
    assert result == answer
"""


def _body_t4(fk: str, i: int) -> str:
    fn = f"test_gen4_{fk}_step_{i:03d}"
    sk = f"step_{i:03d}_t4"
    return f"""
def {fn}():
    cap = json.loads((_FIXTURE_DIR / "{fk}" / "capture.json").read_text())
    entry = cap["entries"][{i}]
    hfile = entry.get("hierarchy_file")
    if not hfile:
        pytest.skip("no hierarchy for this step")
    inp = entry["input"]
    x = inp.get("x", inp.get("x1", inp.get("target_x")))
    y = inp.get("y", inp.get("y1", inp.get("target_y")))
    if x is None or y is None:
        pytest.skip("no coordinates for this step")
    root = ET.fromstring((_FIXTURE_DIR / "{fk}" / hfile).read_text())
    el = hit_test(x, y, root)
    quality = get_selector_quality(el) if el is not None else "coordinate"
    result = {{"quality": quality, "is_problematic": quality in _WARN_QUALITIES}}
    answer = _load_or_store("{fk}", "{sk}", result)
    assert result == answer
"""


def _body_t5(fk: str, i: int) -> str:
    fn = f"test_gen5_{fk}_step_{i:03d}"
    sk = f"step_{i:03d}_t5"
    return f"""
def {fn}():
    cap = json.loads((_FIXTURE_DIR / "{fk}" / "capture.json").read_text())
    step = {{k: v for k, v in cap["entries"][{i}]["output"].items() if k != "timestamp"}}
    code = generate_script([step], "test_case")
    answer = _load_or_store("{fk}", "{sk}", code)
    assert code == answer
"""


def _body_t3_xpath(fk: str, i: int) -> str:
    fn = f"test_gen3b_{fk}_step_{i:03d}"
    sk = f"step_{i:03d}_t3b"
    return f"""
def {fn}():
    cap = json.loads((_FIXTURE_DIR / "{fk}" / "capture.json").read_text())
    entry = cap["entries"][{i}]
    hfile = entry.get("hierarchy_file_xpath")
    if not hfile:
        pytest.skip("no xpath-variant hierarchy for this step")
    inp = entry["input"]
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "{fk}" / hfile).read_text())
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {{k: v for k, v in step.items() if k not in _STRIP_KEYS}}
    answer = _load_or_store("{fk}", "{sk}", result)
    assert result == answer
"""


_BODY_FNS = {1: _body_t1, 2: _body_t2, 3: _body_t3, 4: _body_t4, 5: _body_t5, 6: _body_t3_xpath}

_SCREENSHOT_ACTIONS = frozenset({"verify_screenshot_gt", "verify_screenshot_diff"})


def _should_skip(test_num: int, entry: dict) -> bool:
    """Return True if the test for this entry would always be skipped."""
    if test_num in (2, 4):
        return not entry.get("hierarchy_file")
    if test_num in (1, 3):
        inp = entry.get("input", {})
        return inp.get("action") in _SCREENSHOT_ACTIONS and "bounds" not in inp
    if test_num == 6:
        return not entry.get("hierarchy_file_xpath")
    return False


# ── Public API ─────────────────────────────────────────────────────────────────

def generate_unit_tests(fixture_key: str, entry_count: int) -> List[str]:
    """Append test functions for each captured entry to the 5 gen test files.

    Args:
        fixture_key:  Folder name under test_unittest/fixtures/ (e.g. 'MyTest_20260603_143510').
        entry_count:  Number of entries in the capture (= number of recorded steps).

    Returns:
        Relative paths of test files that were written or updated.
    """
    import json as _json
    _TEST_UNITTEST.mkdir(exist_ok=True)

    capture_path = _TEST_UNITTEST / "fixtures" / fixture_key / "capture.json"
    entries = _json.loads(capture_path.read_text(encoding="utf-8"))["entries"] if capture_path.exists() else []

    updated: List[str] = []

    for test_num, (filename, desc) in _FILES.items():
        path = _TEST_UNITTEST / filename
        existing = path.read_text(encoding="utf-8") if path.exists() else _file_header(desc)

        new_funcs: List[str] = []
        for i in range(entry_count):
            fn_name = f"test_gen{test_num}_{fixture_key}_step_{i:03d}"
            if fn_name in existing:
                continue
            if i < len(entries) and _should_skip(test_num, entries[i]):
                continue
            new_funcs.append(_BODY_FNS[test_num](fixture_key, i))

        if not new_funcs:
            continue

        block_hdr = f"# ── {fixture_key}"
        additions = ""
        if block_hdr not in existing:
            bar = "─" * max(1, 74 - len(fixture_key))
            additions += f"\n\n{block_hdr} {bar}\n"
        additions += "".join(new_funcs)

        path.write_text(existing + additions, encoding="utf-8")
        rel = str(path.relative_to(_TEST_UNITTEST.parent))
        if rel not in updated:
            updated.append(rel)

    return updated
