"""
Auto-generated by iOS Recorder --unit_test mode. Append-only.
Test 1 — Action + Coordinates: call recorder directly, verify action + coords
"""
import asyncio
import json
import xml.etree.ElementTree as ET
from pathlib import Path

import app.main as m
import pytest
from app.hittest import hit_test
from app.selector import build_selector, get_selector_quality
from app.codegen import generate_script

pytestmark = pytest.mark.unit

_FIXTURE_DIR = Path(__file__).parent / "fixtures"
_ANSWERS_DIR = Path(__file__).parent / "answers"
_WARN_QUALITIES = frozenset({"id_indexed", "id_eq_label", "label_only", "xpath_only"})
_STRIP_KEYS = frozenset({"timestamp", "pre_screenshot", "pre_screenshot_size"})


def _call_record_fn(inp: dict):
    """Directly invoke the recorder's _record_* function for the given input."""
    action = inp["action"]
    root = m._cache.get("root")
    if action in ("tap", "double_tap", "triple_tap", "two_finger_tap"):
        asyncio.run(m._record_point(action, inp["x"], inp["y"], root))
    elif action == "long_press":
        asyncio.run(m._record_long_press(inp["x"], inp["y"], inp.get("duration", 1000), root))
    elif action == "multi_finger_tap":
        asyncio.run(m._record_multi_finger_tap(inp["x"], inp["y"], inp.get("fingers", 3), root))
    elif action == "pinch":
        asyncio.run(m._record_pinch(inp["x"], inp["y"], inp["scale"], 80, inp.get("duration", 500), root))
    elif action == "rotate":
        asyncio.run(m._record_rotate(inp["x"], inp["y"], inp["rotation"], 80, root))
    elif action == "scroll":
        asyncio.run(m._record_scroll(inp["x1"], inp["y1"], inp["x2"], inp["y2"], inp.get("duration", 600), root))
    elif action == "swipe":
        asyncio.run(m._record_move("swipe", inp["x1"], inp["y1"], inp["x2"], inp["y2"], inp.get("duration", 400), snapshot=root))
    elif action == "drag":
        asyncio.run(m._record_drag(inp["x1"], inp["y1"], inp["x2"], inp["y2"], inp.get("duration", 1000), root))
    elif action == "type_text":
        asyncio.run(m._record_type_text(inp["text"], inp.get("target_x"), inp.get("target_y"), root))
    elif action == "home":
        asyncio.run(m._record_simple("home"))
    elif action == "launch_app":
        asyncio.run(m._record_launch_app(inp["bundle_id"]))
    elif action == "terminate_app":
        asyncio.run(m._record_terminate_app(inp["bundle_id"]))
    elif action in ("verify_visible", "verify_not_visible"):
        asyncio.run(m._record_verify_visible(inp["target_x"], inp["target_y"],
                                              action == "verify_not_visible", root))
    elif action == "verify_get_text":
        asyncio.run(m._record_verify_get_text(inp["target_x"], inp["target_y"], inp["expected_text"]))
    elif action == "verify_screenshot_gt":
        if "bounds" not in inp:
            pytest.skip("no bounds captured for verify_screenshot_gt")
        asyncio.run(m._record_verify_screenshot_gt(inp["target_x"], inp["target_y"],
                                                   inp["screenshot_name"], inp["bounds"]))
    elif action == "verify_screenshot_diff":
        if "bounds" not in inp:
            pytest.skip("no bounds captured for verify_screenshot_diff")
        asyncio.run(m._record_verify_screenshot_diff(inp["target_x"], inp["target_y"],
                                                     inp["bounds"], inp.get("phase", "before")))
    else:
        pytest.skip(f"unsupported action: {action}")


def _load_or_store(fixture_key: str, step_key: str, result):
    """Fail on first run (saving result as answer); compare on subsequent runs."""
    _ANSWERS_DIR.mkdir(exist_ok=True)
    answer_file = _ANSWERS_DIR / f"{fixture_key}.json"
    answers = json.loads(answer_file.read_text()) if answer_file.exists() else {}
    if step_key not in answers:
        answers[step_key] = result
        answer_file.write_text(json.dumps(answers, ensure_ascii=False, indent=2))
        pytest.fail(f"No answer — result saved as new answer:\n{json.dumps(result, ensure_ascii=False, indent=2)}")
    return answers[step_key]



# ── Canva_20260604_114332 ─────────────────────────────────────────────────────

def test_gen1_Canva_20260604_114332_step_000():
    cap = json.loads((_FIXTURE_DIR / "Canva_20260604_114332" / "capture.json").read_text())
    entry = cap["entries"][0]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_20260604_114332" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_20260604_114332", "step_000_t1", result)
    assert result == answer

def test_gen1_Canva_20260604_114332_step_001():
    cap = json.loads((_FIXTURE_DIR / "Canva_20260604_114332" / "capture.json").read_text())
    entry = cap["entries"][1]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_20260604_114332" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_20260604_114332", "step_001_t1", result)
    assert result == answer

def test_gen1_Canva_20260604_114332_step_002():
    cap = json.loads((_FIXTURE_DIR / "Canva_20260604_114332" / "capture.json").read_text())
    entry = cap["entries"][2]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_20260604_114332" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_20260604_114332", "step_002_t1", result)
    assert result == answer

def test_gen1_Canva_20260604_114332_step_003():
    cap = json.loads((_FIXTURE_DIR / "Canva_20260604_114332" / "capture.json").read_text())
    entry = cap["entries"][3]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_20260604_114332" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_20260604_114332", "step_003_t1", result)
    assert result == answer

def test_gen1_Canva_20260604_114332_step_004():
    cap = json.loads((_FIXTURE_DIR / "Canva_20260604_114332" / "capture.json").read_text())
    entry = cap["entries"][4]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_20260604_114332" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_20260604_114332", "step_004_t1", result)
    assert result == answer

def test_gen1_Canva_20260604_114332_step_005():
    cap = json.loads((_FIXTURE_DIR / "Canva_20260604_114332" / "capture.json").read_text())
    entry = cap["entries"][5]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_20260604_114332" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_20260604_114332", "step_005_t1", result)
    assert result == answer

def test_gen1_Canva_20260604_114332_step_006():
    cap = json.loads((_FIXTURE_DIR / "Canva_20260604_114332" / "capture.json").read_text())
    entry = cap["entries"][6]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_20260604_114332" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_20260604_114332", "step_006_t1", result)
    assert result == answer

def test_gen1_Canva_20260604_114332_step_007():
    cap = json.loads((_FIXTURE_DIR / "Canva_20260604_114332" / "capture.json").read_text())
    entry = cap["entries"][7]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_20260604_114332" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_20260604_114332", "step_007_t1", result)
    assert result == answer

def test_gen1_Canva_20260604_114332_step_008():
    cap = json.loads((_FIXTURE_DIR / "Canva_20260604_114332" / "capture.json").read_text())
    entry = cap["entries"][8]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_20260604_114332" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_20260604_114332", "step_008_t1", result)
    assert result == answer


# ── Canva_Text_20260604_114431 ────────────────────────────────────────────────

def test_gen1_Canva_Text_20260604_114431_step_000():
    cap = json.loads((_FIXTURE_DIR / "Canva_Text_20260604_114431" / "capture.json").read_text())
    entry = cap["entries"][0]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_Text_20260604_114431" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_Text_20260604_114431", "step_000_t1", result)
    assert result == answer

def test_gen1_Canva_Text_20260604_114431_step_001():
    cap = json.loads((_FIXTURE_DIR / "Canva_Text_20260604_114431" / "capture.json").read_text())
    entry = cap["entries"][1]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_Text_20260604_114431" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_Text_20260604_114431", "step_001_t1", result)
    assert result == answer

def test_gen1_Canva_Text_20260604_114431_step_002():
    cap = json.loads((_FIXTURE_DIR / "Canva_Text_20260604_114431" / "capture.json").read_text())
    entry = cap["entries"][2]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_Text_20260604_114431" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_Text_20260604_114431", "step_002_t1", result)
    assert result == answer

def test_gen1_Canva_Text_20260604_114431_step_003():
    cap = json.loads((_FIXTURE_DIR / "Canva_Text_20260604_114431" / "capture.json").read_text())
    entry = cap["entries"][3]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_Text_20260604_114431" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_Text_20260604_114431", "step_003_t1", result)
    assert result == answer


# ── Canva_Pinch_Rotate_20260604_114557 ────────────────────────────────────────

def test_gen1_Canva_Pinch_Rotate_20260604_114557_step_000():
    cap = json.loads((_FIXTURE_DIR / "Canva_Pinch_Rotate_20260604_114557" / "capture.json").read_text())
    entry = cap["entries"][0]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_Pinch_Rotate_20260604_114557" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_Pinch_Rotate_20260604_114557", "step_000_t1", result)
    assert result == answer

def test_gen1_Canva_Pinch_Rotate_20260604_114557_step_001():
    cap = json.loads((_FIXTURE_DIR / "Canva_Pinch_Rotate_20260604_114557" / "capture.json").read_text())
    entry = cap["entries"][1]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Canva_Pinch_Rotate_20260604_114557" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Canva_Pinch_Rotate_20260604_114557", "step_001_t1", result)
    assert result == answer


# ── Swipe_20260604_114637 ─────────────────────────────────────────────────────

def test_gen1_Swipe_20260604_114637_step_000():
    cap = json.loads((_FIXTURE_DIR / "Swipe_20260604_114637" / "capture.json").read_text())
    entry = cap["entries"][0]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Swipe_20260604_114637" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Swipe_20260604_114637", "step_000_t1", result)
    assert result == answer


# ── Home_Switch_Kill_20260604_114722 ──────────────────────────────────────────

def test_gen1_Home_Switch_Kill_20260604_114722_step_000():
    cap = json.loads((_FIXTURE_DIR / "Home_Switch_Kill_20260604_114722" / "capture.json").read_text())
    entry = cap["entries"][0]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Home_Switch_Kill_20260604_114722" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Home_Switch_Kill_20260604_114722", "step_000_t1", result)
    assert result == answer

def test_gen1_Home_Switch_Kill_20260604_114722_step_001():
    cap = json.loads((_FIXTURE_DIR / "Home_Switch_Kill_20260604_114722" / "capture.json").read_text())
    entry = cap["entries"][1]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Home_Switch_Kill_20260604_114722" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Home_Switch_Kill_20260604_114722", "step_001_t1", result)
    assert result == answer

def test_gen1_Home_Switch_Kill_20260604_114722_step_002():
    cap = json.loads((_FIXTURE_DIR / "Home_Switch_Kill_20260604_114722" / "capture.json").read_text())
    entry = cap["entries"][2]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Home_Switch_Kill_20260604_114722" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Home_Switch_Kill_20260604_114722", "step_002_t1", result)
    assert result == answer


# ── Verify_visible_nonVsible_text_20260604_115547 ─────────────────────────────

def test_gen1_Verify_visible_nonVsible_text_20260604_115547_step_000():
    cap = json.loads((_FIXTURE_DIR / "Verify_visible_nonVsible_text_20260604_115547" / "capture.json").read_text())
    entry = cap["entries"][0]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Verify_visible_nonVsible_text_20260604_115547" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Verify_visible_nonVsible_text_20260604_115547", "step_000_t1", result)
    assert result == answer

def test_gen1_Verify_visible_nonVsible_text_20260604_115547_step_001():
    cap = json.loads((_FIXTURE_DIR / "Verify_visible_nonVsible_text_20260604_115547" / "capture.json").read_text())
    entry = cap["entries"][1]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Verify_visible_nonVsible_text_20260604_115547" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Verify_visible_nonVsible_text_20260604_115547", "step_001_t1", result)
    assert result == answer

def test_gen1_Verify_visible_nonVsible_text_20260604_115547_step_002():
    cap = json.loads((_FIXTURE_DIR / "Verify_visible_nonVsible_text_20260604_115547" / "capture.json").read_text())
    entry = cap["entries"][2]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Verify_visible_nonVsible_text_20260604_115547" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Verify_visible_nonVsible_text_20260604_115547", "step_002_t1", result)
    assert result == answer

def test_gen1_Verify_visible_nonVsible_text_20260604_115547_step_003():
    cap = json.loads((_FIXTURE_DIR / "Verify_visible_nonVsible_text_20260604_115547" / "capture.json").read_text())
    entry = cap["entries"][3]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Verify_visible_nonVsible_text_20260604_115547" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Verify_visible_nonVsible_text_20260604_115547", "step_003_t1", result)
    assert result == answer

def test_gen1_Verify_visible_nonVsible_text_20260604_115547_step_004():
    cap = json.loads((_FIXTURE_DIR / "Verify_visible_nonVsible_text_20260604_115547" / "capture.json").read_text())
    entry = cap["entries"][4]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Verify_visible_nonVsible_text_20260604_115547" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Verify_visible_nonVsible_text_20260604_115547", "step_004_t1", result)
    assert result == answer


# ── Verify_GT_Diff_20260604_143914 ────────────────────────────────────────────

def test_gen1_Verify_GT_Diff_20260604_143914_step_001():
    cap = json.loads((_FIXTURE_DIR / "Verify_GT_Diff_20260604_143914" / "capture.json").read_text())
    entry = cap["entries"][1]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Verify_GT_Diff_20260604_143914" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Verify_GT_Diff_20260604_143914", "step_001_t1", result)
    assert result == answer

def test_gen1_Verify_GT_Diff_20260604_143914_step_002():
    cap = json.loads((_FIXTURE_DIR / "Verify_GT_Diff_20260604_143914" / "capture.json").read_text())
    entry = cap["entries"][2]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Verify_GT_Diff_20260604_143914" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Verify_GT_Diff_20260604_143914", "step_002_t1", result)
    assert result == answer

def test_gen1_Verify_GT_Diff_20260604_143914_step_003():
    cap = json.loads((_FIXTURE_DIR / "Verify_GT_Diff_20260604_143914" / "capture.json").read_text())
    entry = cap["entries"][3]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Verify_GT_Diff_20260604_143914" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Verify_GT_Diff_20260604_143914", "step_003_t1", result)
    assert result == answer

def test_gen1_Verify_GT_Diff_20260604_143914_step_004():
    cap = json.loads((_FIXTURE_DIR / "Verify_GT_Diff_20260604_143914" / "capture.json").read_text())
    entry = cap["entries"][4]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Verify_GT_Diff_20260604_143914" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Verify_GT_Diff_20260604_143914", "step_004_t1", result)
    assert result == answer

def test_gen1_Tap_2f_3finger_20260604_143948_step_000():
    cap = json.loads((_FIXTURE_DIR / "Tap_2f_3finger_20260604_143948" / "capture.json").read_text())
    entry = cap["entries"][0]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Tap_2f_3finger_20260604_143948" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Tap_2f_3finger_20260604_143948", "step_000_t1", result)
    assert result == answer

def test_gen1_Tap_2f_3finger_20260604_143948_step_001():
    cap = json.loads((_FIXTURE_DIR / "Tap_2f_3finger_20260604_143948" / "capture.json").read_text())
    entry = cap["entries"][1]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Tap_2f_3finger_20260604_143948" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Tap_2f_3finger_20260604_143948", "step_001_t1", result)
    assert result == answer


# ── tap_5_20260608_155442 ─────────────────────────────────────────────────────

def test_gen1_tap_5_20260608_155442_step_000():
    cap = json.loads((_FIXTURE_DIR / "tap_5_20260608_155442" / "capture.json").read_text())
    entry = cap["entries"][0]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "tap_5_20260608_155442" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("tap_5_20260608_155442", "step_000_t1", result)
    assert result == answer

def test_gen1_tap_5_20260608_155442_step_001():
    cap = json.loads((_FIXTURE_DIR / "tap_5_20260608_155442" / "capture.json").read_text())
    entry = cap["entries"][1]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "tap_5_20260608_155442" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("tap_5_20260608_155442", "step_001_t1", result)
    assert result == answer

# ── PromptBox_20260609_114419 ─────────────────────────────────────────────────

def test_gen1_PromptBox_20260609_114419_step_000():
    cap = json.loads((_FIXTURE_DIR / "PromptBox_20260609_114419" / "capture.json").read_text())
    entry = cap["entries"][0]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "PromptBox_20260609_114419" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("PromptBox_20260609_114419", "step_000_t1", result)
    assert result == answer


# ── TypeText_20260609_140326 ──────────────────────────────────────────────────

def test_gen1_TypeText_20260609_140326_step_000():
    cap = json.loads((_FIXTURE_DIR / "TypeText_20260609_140326" / "capture.json").read_text())
    entry = cap["entries"][0]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "TypeText_20260609_140326" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("TypeText_20260609_140326", "step_000_t1", result)
    assert result == answer


# ── Drag_20260609_151706 ──────────────────────────────────────────────────────

def test_gen1_Drag_20260609_151706_step_000():
    cap = json.loads((_FIXTURE_DIR / "Drag_20260609_151706" / "capture.json").read_text())
    entry = cap["entries"][0]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "Drag_20260609_151706" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("Drag_20260609_151706", "step_000_t1", result)
    assert result == answer


# ── LongPress8_20260609_164342 ────────────────────────────────────────────────

def test_gen1_LongPress8_20260609_164342_step_001():
    cap = json.loads((_FIXTURE_DIR / "LongPress8_20260609_164342" / "capture.json").read_text())
    entry = cap["entries"][1]
    inp = entry["input"]
    hfile = entry.get("hierarchy_file")
    m._cache["root"] = ET.fromstring((_FIXTURE_DIR / "LongPress8_20260609_164342" / hfile).read_text()) if hfile else None
    m._steps.clear()
    _call_record_fn(inp)
    assert m._steps, "no step recorded"
    step = m._steps[-1]
    result = {"action": step["action"]}
    if "coords" in step:
        result["coords"] = step["coords"]
    answer = _load_or_store("LongPress8_20260609_164342", "step_001_t1", result)
    assert result == answer
